import { Platform, StyleSheet } from 'react-native';

export const loginStyles = StyleSheet.create({
  backRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 12,
  },
  backText: {
    color: '#2FC4B1',
    fontSize: 14,
    fontFamily: 'SulphurPoint',
  },
  title: {
    fontSize: 28,
    fontWeight: '800',
    color: '#117C72',
    letterSpacing: 2,
    marginBottom: 12,
    fontFamily: Platform.OS === 'ios' ? 'SulphurPointBold' : 'serif',
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    color: '#2FC4B1',
    marginBottom: 4,
    marginTop: 14,
    letterSpacing: 0.5,
    fontFamily: Platform.OS === 'ios' ? 'SulphurPointBold' : 'serif',
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1.5,
    borderBottomColor: '#2FC4B1',
    paddingBottom: 8,
    marginBottom: 2,
  },
  input: {
    flex: 1,
    fontSize: 15,
    color: '#575757',
    fontFamily: Platform.OS === 'ios' ? 'SulphurPoint' : 'serif',
    paddingVertical: 4,
  },
  helpRow: {
    marginTop: 18,
    alignItems: 'flex-start',
  },
  secondaryPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: '#F4FBF9',
    borderWidth: 1,
    borderColor: '#D7F2EB',
  },
  secondaryPillText: {
    color: '#117C72',
    fontSize: 14,
    fontWeight: '700',
    fontFamily: Platform.OS === 'ios' ? 'SulphurPointBold' : 'serif',
  },
  button: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2FC4B1',
    borderRadius: 30,
    paddingVertical: 16,
    marginTop: 24,
    gap: 8,
    shadowColor: '#2FC4B1',
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 6,
  },
  buttonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.5,
    fontFamily: Platform.OS === 'ios' ? 'SulphurPointBold' : 'serif',
  },
  linkContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 20,
  },
  linkText: {
    fontSize: 14,
    color: '#9AA8A0',
  },
  linkBold: {
    color: '#2FC4B1',
    fontWeight: '700',
  },
});
