import { StyleSheet } from 'react-native';

export const authScreenStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FFF' },
  imageI: {
    position: 'absolute',
    top: 160,
    left: 0,
    width: '100%',
    height: '85%',
    zIndex: 1,
  },
  imageS: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '49%',
    zIndex: 1,
  },
  logoText: {
    position: 'absolute',
    top: 100,
    alignSelf: 'center',
    fontSize: 67,
    letterSpacing: 4,
    color: '#117C72',
    fontFamily: 'SulphurPointBold',
    zIndex: 10,
  },
  introLogoText: {
    position: 'absolute',
    top: 100,
    alignSelf: 'center',
    fontSize: 52,
    color: '#117C72',
    fontFamily: 'SulphurPointBold',
    zIndex: 10,
  },
  panelWrapper: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    zIndex: 2,
  },
  card: {
    backgroundColor: '#FFFF',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    paddingHorizontal: 28,
    paddingTop: 24,
    paddingBottom: 40,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 8,
  },
  vistaContainer: {
    flex: 1,
    justifyContent: 'center',
  },
  panelTitle: {
    marginBottom: 12,
    fontSize: 24,
    textAlign: 'center',
    color: '#117C72',
    fontFamily: 'SulphurPointBold',
  },
  saludo: {
    textAlign: 'center',
    color: '#555',
    fontFamily: 'SulphurPoint',
  },
  saludodos: {
    textAlign: 'center',
    color: '#555',
    fontFamily: 'SulphurPointBold',
  },
  buttonLogin: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2FC4B1',
    borderRadius: 500,
    paddingVertical: 14,
    width: '83%',
    alignSelf: 'center',
    marginTop: 28,
    shadowColor: '#25d4bc',
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 5,
  },
  buttonRegister: {
    marginTop: 16,
    paddingVertical: 14,
    borderRadius: 500,
    width: '75%',
    alignSelf: 'center',
    alignItems: 'center',
    backgroundColor: '#FCFCFC',
    shadowColor: '#a3a3a3',
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 3,
  },
  buttonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  buttonTextLogin: {
    fontSize: 18,
    color: '#FFF',
    fontFamily: 'SulphurPointBold',
  },
  buttonTextRegister: {
    fontSize: 18,
    color: '#2FC4B1',
    fontFamily: 'SulphurPointBold',
  },
});
