import { StyleSheet } from 'react-native';

export const registerStyles = StyleSheet.create({
  backRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    marginTop: 8,
    marginBottom: 8,
  },
  backText: {
    color: '#2FC4B1',
    fontSize: 14,
    fontFamily: 'SulphurPoint',
  },
  title: {
    fontSize: 28,
    fontWeight: '800',
    color: '#117C72',
    letterSpacing: 2,
    marginTop: 16,
    fontFamily: 'SulphurPointBold',
  },
  photoButton: {
    position: 'absolute',
    top: 10,
    right: 18,
    width: 76,
    height: 76,
    backgroundColor: '#F7FFFC',
    borderRadius: 38,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0000003d',
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#D3F2EB',
  },
  photoPlaceholder: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F7FFFC',
  },
  photoPreview: {
    width: '100%',
    height: '100%',
  },
  photoText: {
    fontSize: 10,
    color: '#2FC4B1',
    fontWeight: '600',
    marginTop: 2,
    textAlign: 'center',
  },
  photoHint: {
    marginTop: 28,
    marginBottom: 0,
    fontSize: 12,
    color: '#8AA69C',
    fontFamily: 'PoppinsRegular',
  },
  label: {
    fontSize: 17,
    fontWeight: '600',
    color: '#2FC4B1',
    marginBottom: 3,
    marginTop: 20,
    letterSpacing: 0,
    fontFamily: 'SulphurPointBold',
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1.5,
    borderBottomColor: '#2FC4B1',
    paddingBottom: 5,
    marginBottom: 0,
  },
  inputIcon: {
    marginRight: 5,
  },
  input: {
    flex: 1,
    fontSize: 15,
    color: '#575757',
    fontFamily: 'PoppinsRegular',
    paddingVertical: 2,
  },
  passwordHint: {
    marginTop: 15,
    fontSize: 12,
    color: '#8AA69C',
    fontFamily: 'PoppinsRegular',
  },
  dropdown: {
    backgroundColor: 'transparent',
    borderRadius: 0,
    marginTop: 7,
    marginBottom: 8,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#FCFCFC',
  },
  dropdownItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#05ed946e',
  },
  dropdownText: {
    fontSize: 15,
    color: '#9AA8A0',
    fontFamily: 'PoppinsRegular',
  },
  dropdownTextActive: {
    color: '#2FC4B1',
    fontWeight: '600',
  },
  button: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2FC4B1',
    borderRadius: 30,
    paddingVertical: 16,
    marginTop: 16,
    gap: 8,
    shadowColor: '#2FC4B1',
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 6,
  },
  buttonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.5,
    fontFamily: 'PoppinsSemiBold',
  },
  linkContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 12,
  },
  linkText: {
    fontSize: 14,
    color: '#9AA8A0',
    fontFamily: 'PoppinsRegular',
  },
  linkBold: {
    color: '#2FC4B1',
    fontWeight: '700',
    fontFamily: 'PoppinsSemiBold',
  },
});
