import { Platform, StyleSheet } from 'react-native';

export const verifyStyles = StyleSheet.create({
  backRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 12,
  },
  backText: {
    color: '#2FC4B1',
    fontSize: 14,
    fontFamily: 'SulphurPoint',
  },
  title: {
    fontSize: 28,
    fontWeight: '800',
    color: '#117C72',
    letterSpacing: 2,
    marginBottom: 12,
    fontFamily: Platform.OS === 'ios' ? 'SulphurPointBold' : 'serif',
  },
  subtitle: {
    fontSize: 15,
    lineHeight: 22,
    color: '#64817A',
    marginBottom: 18,
    fontFamily: Platform.OS === 'ios' ? 'SulphurPoint' : 'serif',
  },
  emailPill: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#E8FBF6',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#D4F2EA',
  },
  emailText: {
    color: '#117C72',
    fontSize: 13,
    fontWeight: '700',
    fontFamily: Platform.OS === 'ios' ? 'SulphurPointBold' : 'serif',
  },
  stepsCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#D6F1EA',
    backgroundColor: '#F7FFFC',
    paddingHorizontal: 18,
    paddingVertical: 18,
    gap: 14,
    marginBottom: 16,
    shadowColor: '#8FD7C6',
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 1,
  },
  stepRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  stepBadge: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#DDF7F0',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#C8EFE4',
  },
  stepBadgeText: {
    color: '#117C72',
    fontSize: 14,
    fontWeight: '700',
    fontFamily: Platform.OS === 'ios' ? 'SulphurPointBold' : 'serif',
  },
  stepText: {
    flex: 1,
    color: '#5E7B73',
    fontSize: 14,
    lineHeight: 20,
    fontFamily: Platform.OS === 'ios' ? 'SulphurPoint' : 'serif',
  },
  helperText: {
    fontSize: 13,
    color: '#8AA69C',
    marginBottom: 24,
    lineHeight: 20,
    fontFamily: Platform.OS === 'ios' ? 'SulphurPoint' : 'serif',
  },
  primaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2FC4B1',
    borderRadius: 16,
    minHeight: 48,
    paddingVertical: 13,
    gap: 8,
    shadowColor: '#2FC4B1',
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 2,
  },
  primaryButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
    fontFamily: Platform.OS === 'ios' ? 'SulphurPointBold' : 'serif',
  },
  secondaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 16,
    paddingVertical: 12,
    marginTop: 14,
    backgroundColor: '#F4FBF9',
    borderWidth: 1,
    borderColor: '#D7F2EB',
    gap: 8,
  },
  secondaryButtonDisabled: {
    opacity: 0.58,
  },
  secondaryButtonText: {
    color: '#117C72',
    fontSize: 15,
    fontWeight: '700',
    fontFamily: Platform.OS === 'ios' ? 'SulphurPointBold' : 'serif',
  },
});
